<?php
namespace App\Controller;
use App\Entity\Groupe;
use App\Form\GroupeType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;



class GroupeController extends AbstractController {

    /**
     * @Route("/groupes" , name="groupes")
     * 
     */
    public function index(Request $request) {

        $em = $this->getDoctrine()->getManager();
        $groupes = $em->getRepository('App\Entity\Groupe')->findAll();

        return $this->render('groupe/index.html.twig', [
                    'groupes' => $groupes
                        ]
        );
    }

    /**
     * @Route("/addGroupe" , name="add-groupe")
     * 
     */
    public function addGroupe(Request $request) {

        $em = $this->getDoctrine()->getManager();
        $groupe = new Groupe();
        $form = $this->createForm(GroupeType::class, $groupe);


        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            
            $photoCouverture = $form->get('photoCouverture')->getData();
            $photoCouvertureName = $this->generateUniqueFileName() . '.' . $photoCouverture->guessExtension();
            $photoGroupe= $form->get('photoGroupe')->getData();
            $photoGroupeName = $this->generateUniqueFileName() . '.' . $photoGroupe->guessExtension();

            // Move the file to the directory where brochures are stored
            try {
                $photoCouverture->move($this->getParameter('brochures_directory'), $photoCouvertureName
                );

                $photoGroupe->move($this->getParameter('brochures_directory'), $photoGroupeName
                );
            } catch (FileException $e) {
                
            }

            $groupe->setPhotoCouverture($photoCouvertureName);
            $groupe->setPhotoGroupe($photoGroupeName);




            $em->persist($groupe);
            $em->flush();
            return $this->redirectToRoute('groupes');
        }

        return $this->render('groupe/addGroupe.html.twig', [
                    'form' => $form->createView()
                        ]
        );
    }

    /**
     * @return string
     */
    private function generateUniqueFileName() {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

}
