#index:
#    path: /
#    controller: App\Controller\DefaultController::index


#home:
#    path: /home
#    controller: App\Controller\HomeController::index


logout:
    path: /logout
    controller: App\Controller\SecurityController::Logout
    
users:
    path: /users
    controller: App\Controller\UserController::index

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"